name: easy_note
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 4.0.2+12

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  screen_manager: ^1.0.0
  font_awesome_flutter: ^10.3.0
  flutter_svg: ^2.2.0
  url_launcher: ^6.1.7
  flutter_slidable: ^4.0.0
  introduction_screen: ^3.1.2
  sqflite: ^2.2.2
  path_provider: ^2.0.11
  path: ^1.8.2
  image_picker: ^1.1.2
  intl: ^0.20.2

  cupertino_icons: ^1.0.2
  flutter_quill: ^11.4.2
  flutter_quill_extensions: ^11.0.0
  tuple: ^2.0.1
  speech_to_text: ^7.3.0
  avatar_glow: ^3.0.1
  share_plus: ^11.1.0
  vsc_quill_delta_to_html: ^1.0.1+1
  html_to_pdf_plus:
    git:
      url: https://github.com/niypoo/html_to_pdf_plus.git
      ref: 2014b75
  flutter_pdfview: ^1.2.5
  flutter_local_notifications: ^19.4.0
  timezone: ^0.10.1
  flutter_datetime_picker_plus: ^2.2.0   # ← trocado aqui
  shared_preferences: ^2.0.18
  custom_refresh_indicator: ^4.0.1
  rive: ^0.13.20
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/easy-note-logo.png
    - lib/assets/images/coffee.svg
    - lib/assets/images/sem-anotacao.svg
    - lib/assets/images/loading_animation.riv
    - lib/assets/images/versoes/3.0/anotacoes.svg
    - lib/assets/images/versoes/3.0/configuracoes.svg
    - lib/assets/images/versoes/3.0/nova-secao.svg
    - lib/assets/images/versoes/3.0/ultima-atualizacao.svg
    - lib/assets/images/versoes/4.0/agendamento.svg
    - lib/assets/images/versoes/4.0/tempo.svg
    - lib/assets/images/anotacao/1.jpg
    - lib/assets/images/anotacao/2.jpg
    - lib/assets/images/anotacao/3.jpg
    - lib/assets/images/anotacao/4.jpg
    - lib/assets/images/anotacao/5.jpg
    - lib/assets/images/anotacao/6.jpg
    - lib/assets/images/anotacao/7.jpg
    - lib/assets/images/anotacao/1-thumbnail.jpg
    - lib/assets/images/anotacao/2-thumbnail.jpg
    - lib/assets/images/anotacao/3-thumbnail.jpg
    - lib/assets/images/anotacao/4-thumbnail.jpg
    - lib/assets/images/anotacao/5-thumbnail.jpg
    - lib/assets/images/anotacao/6-thumbnail.jpg
    - lib/assets/images/anotacao/7-thumbnail.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: monospace
      fonts:
        - asset: lib/assets/fonts/MonoSpace.ttf
    - family: serif
      fonts:
        - asset: lib/assets/fonts/Serif.ttf
    - family: sans-serif
      fonts:
        - asset: lib/assets/fonts/SansSerif.ttf
    - family: ibarra-real-nova
      fonts:
          - asset: lib/assets/fonts/IbarraRealNova-Regular.ttf
    - family: square-peg
      fonts:
        - asset: lib/assets/fonts/SquarePeg-Regular.ttf
    - family: nunito
      fonts:
        - asset: lib/assets/fonts/Nunito-Regular.ttf
    - family: pacifico
      fonts:
        - asset: lib/assets/fonts/Pacifico-Regular.ttf
    - family: roboto-mono
      fonts:
        - asset: lib/assets/fonts/RobotoMono-Regular.ttf
    - family: roboto
      fonts:
        - asset: lib/assets/fonts/Roboto-Regular.ttf
    - family: helvetica-neue
      fonts:
        - asset: lib/assets/fonts/helveticaneue.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
