final mensagens = {
  1: "Ei, você se lembra daquela anotação que você fez? 📝",
  2: "Não se esqueça daquele lembrete importante que você anotou! 🔔",
  3: "Tem algo importante para você lembrar - confira suas anotações! 🤔",
  4: "Lembre-se de verificar suas anotações para não perder nada! 🧐",
  5: "Aquela anotação que você fez pode ser útil agora - dê uma olhada! 👀",
  6: "Um lembrete amigável para dar uma olhada nas suas anotações! 🧑‍🤝‍🧑",
  7: "Não esqueça de verificar suas anotações para manter-se organizado! 📋",
  8: "Lembre-se de conferir suas anotações para ficar sempre atualizado! 🕵️‍♀️",
  9: "Hora de dar uma olhada naquela anotação importante que você fez! ⏰",
  10: "Verifique suas anotações para não perder nenhuma informação valiosa! 💡",
  11: "Não se esqueça de conferir suas anotações para manter-se no caminho certo! 🚀",
  12: "Lembre-se daquela anotação importante que você fez - pode ser útil agora! 🤞",
  13: "Não deixe suas anotações acumularem - confira agora! 📌",
  14: "Dê uma olhada nas suas anotações para garantir que nada seja esquecido! 🧠",
  15: "Confira suas anotações para manter-se organizado e produtivo! 📈",
  16: "Não se esqueça daquela ideia brilhante que você anotou! 💡",
  17: "Sua anotação pode ser útil agora - verifique para ter certeza! 🤔",
  18: "Lembre-se de que a informação que você precisa pode estar em suas anotações! 🕵️‍♂️",
  19: "Não deixe suas anotações ficarem esquecidas - confira agora! 👀",
  20: "Dê uma olhada nas suas anotações para manter-se no topo das coisas! 📝",
  21: "Não se esqueça de verificar suas anotações antes de tomar uma decisão importante! 🤞",
  22: "Lembre-se de que suas anotações são uma ferramenta valiosa - use-as! 🔧",
  23: "Não perca tempo - confira suas anotações agora! ⌛",
  24: "Sua anotação pode ser a chave para resolver um problema - dê uma olhada! 🔑",
  25: "Não se esqueça de conferir suas anotações para manter-se no caminho certo! 🏃‍♂️",
  26: "Lembre-se de que suas anotações podem ajudá-lo a ser mais produtivo! 📈",
  27: "Não deixe suas ideias escaparem - anote-as e verifique regularmente! 🤔",
  28: "Dê uma olhada nas suas anotações para garantir que você não esqueça nada importante! 🚨",
  29: "Não se esqueça de verificar suas anotações antes de uma reunião importante! 🤝",
  30: "Sua anotação pode ser a solução para um problema - verifique agora! 💡",
  31: "Lembre-se de que suas anotações são uma fonte valiosa de informação - use-as! 🔎",
  32: "Não deixe suas anotações acumularem - organize-as agora! 🗂️",
  33: "Confira suas anotações para ter certeza de que não perdeu nada importante! 👀",
  34: "Não se esqueça de verificar suas anotações para manter-se no topo das coisas! 📈",
  35: "Sua anotação pode ser a inspiração para um novo projeto - dê uma olhada! 🌟",
  36: "Lembre-se de que suas anotações podem ajudá-lo a tomar melhores decisões! 🤔",
  37: "Não deixe suas anotações ficarem esquecidas - confira regularmente! 📝",
  38: "Dê uma olhada nas suas anotações para garantir que está no caminho certo! 🚶‍♀️",
  39: "Não se esqueça de conferir suas anotações antes de uma entrevista importante! 👔",
  40: "Sua anotação pode ser a resposta para uma pergunta importante - verifique agora! 💬",
  41: "Lembre-se de que suas anotações são uma ferramenta valiosa para a criatividade! 🎨",
  42: "Não deixe suas anotações se perderem - organize-as agora! 🗂️",
  43: "Confira suas anotações para ter certeza de que está sempre atualizado! 📊",
  44: "Não se esqueça de verificar suas anotações antes de uma apresentação importante! 🎤",
  45: "Sua anotação pode ser a chave para resolver um mistério - dê uma olhada! 🔍",
  46: "Lembre-se de que suas anotações podem ajudá-lo a manter-se focado! 🧘‍♀️",
  47: "Não deixe suas anotações acumularem - organize-as regularmente! 📋",
  48: "Dê uma olhada nas suas anotações para garantir que não perdeu nada importante! 🕵️‍♀️",
  49: "Não se esqueça de conferir suas anotações para manter-se no topo das coisas! 🏆",
  50: "Sua anotação pode ser a solução para um problema - verifique agora! 🔍"
};